
te:te.c
	gcc $^ -o $@
review:review.c
	gcc $^ -o $@
test:test.c
	gcc $^ -o $@
minishell:minishell.c
	gcc $^ -o $@
stream:stream.c
	gcc $^ -o $@
redir:redir.c
	gcc $^ -o $@
op:op.c
	gcc $^ -o $@
fp:fp.c
	gcc $^ -o $@
