scalper:scalper.c
	gcc $^ -o $@ -lpthread
return:return.c
	gcc $^ -o $@ -lpthread
pthread_create_num:pthread_create_num.c
	gcc $^ -o $@ -lpthread
pthread_create:pthread_create.c
	gcc $^ -o $@ -lpthread
